name: Deploy to slides repo

on: push

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    name: copy site folder to slides repo

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
